# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0106b98f8a2d0b62d613b04624be370b908320951b5ed477378a784a4ed0f77b55997cccd6f2abfe842b33a31f50ea8571c5b4657ae11d52cf65901e8372b3c7

test:
  secret_key_base: 2bd0226de92a368aac927ca6df3e040fb98e724201c727a6cb8838c77960d2f03a79047d6b7bfa98f305f5ceedb528b69d2fab001fc737dbb2410dc805d59ea5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
